### ISSUE TITLE
Querying non-existant table

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#168] opened 2020-06-19 06:24 UTC
Querying the [NAV_TENANT](https://demo.aircloak.com/data_sources/NAV_W1_TENANT_WS001) data source, there have been queries issued against a non-existent table!

Like:

```sql
                select
                    grouping_id(
                        date_trunc('year', dropoff_datetime),
date_trunc('quarter', dropoff_datetime),
date_trunc('month', dropoff_datetime),
date_trunc('day', dropoff_datetime),
date_trunc('hour', dropoff_datetime),
date_trunc('minute', dropoff_datetime),
date_trunc('second', dropoff_datetime)
                    ),
                    date_trunc('year', dropoff_datetime),
date_trunc('quarter', dropoff_datetime),
date_trunc('month', dropoff_datetime),
date_trunc('day', dropoff_datetime),
date_trunc('hour', dropoff_datetime),
date_trunc('minute', dropoff_datetime),
date_trunc('second', dropoff_datetime),
                    count(*),
                    count_noise(*)
                from year
                group by grouping sets (2, 3, 4, 5, 6, 7, 8)
```

where `year` is not at all a table.

All [errors here](https://demo.aircloak.com/admin/queries/failed?users[]=159&data_sources[]=112&from=2020-06-18+14%3A28%3A00.001295&to=2020-06-18+15%3A35%3A25.992520)

**Comment by dandanlen** [comment] 2020-06-19 08:04
I found the `year` table, it's in the `taxi_year` dataset... 

So it's somehow issuing queries against the wrong dataset.

**Comment by dandanlen** [comment] 2020-11-02 10:22
Closing this issue since 
- I never managed to reproduce it.
- I haven't seen it recur despite the extra logging we have added since the issue was first raised.

**Closed by dandanlen** 2020-11-02 10:22 UTC
Labels: bug
